// Code generated by godepsgen. DO NOT EDIT.
// Source: /mnt/w541-data/shared/GolandProjects/ratatoskr/go.mod
// Generated at: 2026-05-26T15:50:43Z

package without_licenses

// // // // // // // // // //

const (
	cModule0  = "github.com/Arceliar/ironwood"
	cModule1  = "github.com/Arceliar/phony"
	cModule2  = "github.com/bits-and-blooms/bitset"
	cModule3  = "github.com/bits-and-blooms/bloom/v3"
	cModule4  = "github.com/coder/websocket"
	cModule5  = "github.com/gologme/log"
	cModule6  = "github.com/google/btree"
	cModule7  = "github.com/hjson/hjson-go/v4"
	cModule8  = "github.com/kr/text"
	cModule9  = "github.com/quic-go/quic-go"
	cModule10 = "github.com/things-go/go-socks5"
	cModule11 = "github.com/wlynxg/anet"
	cModule12 = "github.com/yggdrasil-network/yggdrasil-go"
	cModule13 = "golang.org/x/crypto"
	cModule14 = "golang.org/x/net"
	cModule15 = "golang.org/x/sys"
	cModule16 = "golang.org/x/text"
	cModule17 = "golang.org/x/time"
	cModule18 = "gopkg.in/yaml.v3"
	cModule19 = "gvisor.dev/gvisor"
)

const (
	cVersion0  = "v0.0.0-20260117132459-7017dbc41d8e"
	cVersion1  = "v0.0.0-20220903101357-530938a4b13d"
	cVersion2  = "v1.24.4"
	cVersion3  = "v3.7.1"
	cVersion4  = "v1.8.14"
	cVersion5  = "v1.3.0"
	cVersion6  = "v1.1.3"
	cVersion7  = "v4.6.0"
	cVersion8  = "v0.2.0"
	cVersion9  = "v0.59.0"
	cVersion10 = "v0.1.1"
	cVersion11 = "v0.0.5"
	cVersion12 = "v0.5.13"
	cVersion13 = "v0.49.0"
	cVersion14 = "v0.52.0"
	cVersion15 = "v0.42.0"
	cVersion16 = "v0.35.0"
	cVersion17 = "v0.15.0"
	cVersion18 = "v3.0.1"
	cVersion19 = "v0.0.0-20250812171554-968e93457fe6"
)

// //

type LicenseObj struct {
	compressedData []byte
	isEmpty        bool
}

type EntryObj struct {
	Module  string
	Version string
	License *LicenseObj
}

//

var (
	license0 = LicenseObj{isEmpty: true}
)

// //

func (item *LicenseObj) String() string {
	return ""
}

// //

var List = []EntryObj{
	{Module: cModule0, Version: cVersion0, License: &license0},
	{Module: cModule1, Version: cVersion1, License: &license0},
	{Module: cModule2, Version: cVersion2, License: &license0},
	{Module: cModule3, Version: cVersion3, License: &license0},
	{Module: cModule4, Version: cVersion4, License: &license0},
	{Module: cModule5, Version: cVersion5, License: &license0},
	{Module: cModule6, Version: cVersion6, License: &license0},
	{Module: cModule7, Version: cVersion7, License: &license0},
	{Module: cModule8, Version: cVersion8, License: &license0},
	{Module: cModule9, Version: cVersion9, License: &license0},
	{Module: cModule10, Version: cVersion10, License: &license0},
	{Module: cModule11, Version: cVersion11, License: &license0},
	{Module: cModule12, Version: cVersion12, License: &license0},
	{Module: cModule13, Version: cVersion13, License: &license0},
	{Module: cModule14, Version: cVersion14, License: &license0},
	{Module: cModule15, Version: cVersion15, License: &license0},
	{Module: cModule16, Version: cVersion16, License: &license0},
	{Module: cModule17, Version: cVersion17, License: &license0},
	{Module: cModule18, Version: cVersion18, License: &license0},
	{Module: cModule19, Version: cVersion19, License: &license0},
}

var VersionByModule = map[string]string{
	cModule0:  cVersion0,
	cModule1:  cVersion1,
	cModule2:  cVersion2,
	cModule3:  cVersion3,
	cModule4:  cVersion4,
	cModule5:  cVersion5,
	cModule6:  cVersion6,
	cModule7:  cVersion7,
	cModule8:  cVersion8,
	cModule9:  cVersion9,
	cModule10: cVersion10,
	cModule11: cVersion11,
	cModule12: cVersion12,
	cModule13: cVersion13,
	cModule14: cVersion14,
	cModule15: cVersion15,
	cModule16: cVersion16,
	cModule17: cVersion17,
	cModule18: cVersion18,
	cModule19: cVersion19,
}

var LicenseByModule = map[string]*LicenseObj{
	cModule0:  &license0,
	cModule1:  &license0,
	cModule2:  &license0,
	cModule3:  &license0,
	cModule4:  &license0,
	cModule5:  &license0,
	cModule6:  &license0,
	cModule7:  &license0,
	cModule8:  &license0,
	cModule9:  &license0,
	cModule10: &license0,
	cModule11: &license0,
	cModule12: &license0,
	cModule13: &license0,
	cModule14: &license0,
	cModule15: &license0,
	cModule16: &license0,
	cModule17: &license0,
	cModule18: &license0,
	cModule19: &license0,
}
