name: 'Initialization of all packages'
description: 'Initialize all the modules and generate files'

runs:
  using: 'composite'
  steps:
    - name: 📥 go mod tidy
      shell: bash
      run: |
        set -Eeuo pipefail
        go mod tidy
